/* Generated By:JJTree&JavaCC: Do not edit this line. AlminParserConstants.java */
package wci.frontend;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AlminParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPACE = 1;
  /** RegularExpression Id. */
  int EOL = 2;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 3;
  /** RegularExpression Id. */
  int GENERAL_COMMENT = 4;
  /** RegularExpression Id. */
  int MAIN = 7;
  /** RegularExpression Id. */
  int TYPE = 8;
  /** RegularExpression Id. */
  int FUNC = 9;
  /** RegularExpression Id. */
  int BODY = 10;
  /** RegularExpression Id. */
  int VAR = 11;
  /** RegularExpression Id. */
  int IF = 12;
  /** RegularExpression Id. */
  int ELSE = 13;
  /** RegularExpression Id. */
  int WHILE = 14;
  /** RegularExpression Id. */
  int FOR = 15;
  /** RegularExpression Id. */
  int RETURN = 16;
  /** RegularExpression Id. */
  int STAR = 17;
  /** RegularExpression Id. */
  int MINUS = 18;
  /** RegularExpression Id. */
  int PLUS = 19;
  /** RegularExpression Id. */
  int ASSIGN = 20;
  /** RegularExpression Id. */
  int SLASH = 21;
  /** RegularExpression Id. */
  int COLON = 22;
  /** RegularExpression Id. */
  int SEMICOLON = 23;
  /** RegularExpression Id. */
  int HOOK = 24;
  /** RegularExpression Id. */
  int LT = 25;
  /** RegularExpression Id. */
  int GT = 26;
  /** RegularExpression Id. */
  int DOT = 27;
  /** RegularExpression Id. */
  int COMMA = 28;
  /** RegularExpression Id. */
  int SINGLEQUOTE = 29;
  /** RegularExpression Id. */
  int DOUBLEQUOTE = 30;
  /** RegularExpression Id. */
  int LPAREN = 31;
  /** RegularExpression Id. */
  int RPAREN = 32;
  /** RegularExpression Id. */
  int LBRACE = 33;
  /** RegularExpression Id. */
  int RBRACE = 34;
  /** RegularExpression Id. */
  int LE = 35;
  /** RegularExpression Id. */
  int GE = 36;
  /** RegularExpression Id. */
  int EQ = 37;
  /** RegularExpression Id. */
  int NE = 38;
  /** RegularExpression Id. */
  int AND = 39;
  /** RegularExpression Id. */
  int OR = 40;
  /** RegularExpression Id. */
  int NOT = 41;
  /** RegularExpression Id. */
  int IDENTIFIER = 42;
  /** RegularExpression Id. */
  int DIGIT = 43;
  /** RegularExpression Id. */
  int LETTER = 44;
  /** RegularExpression Id. */
  int CHAR = 45;
  /** RegularExpression Id. */
  int STRING = 46;
  /** RegularExpression Id. */
  int BOOL = 47;
  /** RegularExpression Id. */
  int INT = 48;
  /** RegularExpression Id. */
  int REAL = 49;
  /** RegularExpression Id. */
  int SIGN = 50;
  /** RegularExpression Id. */
  int UNSIGNED = 51;
  /** RegularExpression Id. */
  int WHOLE = 52;
  /** RegularExpression Id. */
  int FRACTION = 53;
  /** RegularExpression Id. */
  int EXPONENT = 54;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMMENT_STATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<SPACE>",
    "<EOL>",
    "<SINGLE_LINE_COMMENT>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 6>",
    "\"main\"",
    "\"TYPE\"",
    "\"FUNC\"",
    "\"BODY\"",
    "\"VAR\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"for\"",
    "\"return\"",
    "\"*\"",
    "\"-\"",
    "\"+\"",
    "\"=\"",
    "\"/\"",
    "\":\"",
    "\";\"",
    "\"?\"",
    "\"<\"",
    "\">\"",
    "\".\"",
    "\",\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "<IDENTIFIER>",
    "<DIGIT>",
    "<LETTER>",
    "<CHAR>",
    "<STRING>",
    "<BOOL>",
    "<INT>",
    "<REAL>",
    "<SIGN>",
    "<UNSIGNED>",
    "<WHOLE>",
    "<FRACTION>",
    "<EXPONENT>",
  };

}
