/* Generated By:JavaCC: Do not edit this line. AlminParserVisitor.java Version 5.0 */
package wci.frontend;

public interface AlminParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTBlock node, Object data);
  public Object visit(ASTASSIGN node, Object data);
  public Object visit(ASTIfStatement node, Object data);
  public Object visit(ASTLOOP node, Object data);
  public Object visit(ASTFunctionCall node, Object data);
  public Object visit(ASTReturnStatement node, Object data);
  public Object visit(ASTLT node, Object data);
  public Object visit(ASTLE node, Object data);
  public Object visit(ASTGT node, Object data);
  public Object visit(ASTGE node, Object data);
  public Object visit(ASTEQ node, Object data);
  public Object visit(ASTNE node, Object data);
  public Object visit(ASTadd node, Object data);
  public Object visit(ASTsub node, Object data);
  public Object visit(ASTor node, Object data);
  public Object visit(ASTmult node, Object data);
  public Object visit(ASTdiv node, Object data);
  public Object visit(ASTand node, Object data);
  public Object visit(ASTStringLiteral node, Object data);
  public Object visit(ASTLiteral node, Object data);
  public Object visit(ASTVariable node, Object data);
  public Object visit(ASTIndex node, Object data);
  public Object visit(ASTField node, Object data);
}
/* JavaCC - OriginalChecksum=3447985cf853023bec7d00c983fde97f (do not edit this line) */
