/* Generated By:JavaCC: Do not edit this line. AlminParserTreeConstants.java Version 5.0 */
package wci.frontend;

public interface AlminParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTBLOCK = 1;
  public int JJTSTATEMENTS = 2;
  public int JJTASSIGNMENTSTATEMENT = 3;
  public int JJTIFSTATEMENT = 4;
  public int JJTWHILESTATEMENT = 5;
  public int JJTFUNCTIONCALL = 6;
  public int JJTRETURNSTATEMENT = 7;
  public int JJTLT = 8;
  public int JJTLE = 9;
  public int JJTGT = 10;
  public int JJTGE = 11;
  public int JJTEQ = 12;
  public int JJTNE = 13;
  public int JJTADD = 14;
  public int JJTSUB = 15;
  public int JJTOR = 16;
  public int JJTMULT = 17;
  public int JJTDIV = 18;
  public int JJTAND = 19;
  public int JJTSTRINGLITERAL = 20;
  public int JJTLITERAL = 21;
  public int JJTVARIABLE = 22;


  public String[] jjtNodeName = {
    "void",
    "Block",
    "Statements",
    "AssignmentStatement",
    "IfStatement",
    "WhileStatement",
    "FunctionCall",
    "ReturnStatement",
    "LT",
    "LE",
    "GT",
    "GE",
    "EQ",
    "NE",
    "add",
    "sub",
    "or",
    "mult",
    "div",
    "and",
    "StringLiteral",
    "Literal",
    "Variable",
  };
}
/* JavaCC - OriginalChecksum=c0844a05a3b918672d747d988e9dab53 (do not edit this line) */
