/* Generated By:JavaCC: Do not edit this line. AlminParserTreeConstants.java Version 5.0 */
package wci.frontend;

public interface AlminParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTBLOCK = 1;
  public int JJTASSIGNMENTSTATEMENT = 2;
  public int JJTIFSTATEMENT = 3;
  public int JJTLOOP = 4;
  public int JJTFUNCTIONCALL = 5;
  public int JJTRETURNSTATEMENT = 6;
  public int JJTLT = 7;
  public int JJTLE = 8;
  public int JJTGT = 9;
  public int JJTGE = 10;
  public int JJTEQ = 11;
  public int JJTNE = 12;
  public int JJTADD = 13;
  public int JJTSUB = 14;
  public int JJTOR = 15;
  public int JJTMULT = 16;
  public int JJTDIV = 17;
  public int JJTAND = 18;
  public int JJTSTRINGLITERAL = 19;
  public int JJTLITERAL = 20;
  public int JJTVARIABLE = 21;


  public String[] jjtNodeName = {
    "void",
    "Block",
    "AssignmentStatement",
    "IfStatement",
    "LOOP",
    "FunctionCall",
    "ReturnStatement",
    "LT",
    "LE",
    "GT",
    "GE",
    "EQ",
    "NE",
    "add",
    "sub",
    "or",
    "mult",
    "div",
    "and",
    "StringLiteral",
    "Literal",
    "Variable",
  };
}
/* JavaCC - OriginalChecksum=ac83cb93987e9d7e676ca8ddd658f291 (do not edit this line) */
