/* Generated By:JavaCC: Do not edit this line. Assignment7Visitor.java Version 5.0 */
package teamAlumni.frontend;

public interface Assignment7Visitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTCompilationUnit node, Object data);
  public Object visit(ASTConstant node, Object data);
  public Object visit(ASTNewType node, Object data);
  public Object visit(ASTNewTypeDefinition node, Object data);
  public Object visit(ASTFunctionList node, Object data);
  public Object visit(ASTFunctionDeclaration node, Object data);
  public Object visit(ASTFuncVariableDeclaration node, Object data);
  public Object visit(ASTType node, Object data);
  public Object visit(ASTFunctionDefinition node, Object data);
  public Object visit(ASTFunction node, Object data);
  public Object visit(ASTDeclAndStat node, Object data);
  public Object visit(ASTVariableDeclaration node, Object data);
  public Object visit(ASTlessThan node, Object data);
  public Object visit(ASTlessEqual node, Object data);
  public Object visit(ASTgreaterThan node, Object data);
  public Object visit(ASTgreaterEqual node, Object data);
  public Object visit(ASTequal node, Object data);
  public Object visit(ASTnotEqual node, Object data);
  public Object visit(ASTplus node, Object data);
  public Object visit(ASTminus node, Object data);
  public Object visit(ASTmultiply node, Object data);
  public Object visit(ASTdivide node, Object data);
  public Object visit(ASTpositive node, Object data);
  public Object visit(ASTnegative node, Object data);
  public Object visit(ASTConstantLiteral node, Object data);
  public Object visit(ASTLiteral node, Object data);
  public Object visit(ASTBooleanLiteral node, Object data);
  public Object visit(ASTName node, Object data);
  public Object visit(ASTBlockStatement node, Object data);
  public Object visit(ASTAssignmentStatement node, Object data);
  public Object visit(ASTControlStatement node, Object data);
  public Object visit(ASTIfStatement node, Object data);
  public Object visit(ASTWhileStatement node, Object data);
  public Object visit(ASTReturnStatement node, Object data);
  public Object visit(ASTError node, Object data);
}
/* JavaCC - OriginalChecksum=624265b2195447022ededa6aaf2cbb53 (do not edit this line) */
