/* Generated By:JavaCC: Do not edit this line. Assignment7TreeConstants.java Version 5.0 */
package teamAlumni.frontend;

public interface Assignment7TreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTCONSTANT = 1;
  public int JJTNEWTYPE = 2;
  public int JJTNEWTYPEDEFINITION = 3;
  public int JJTFUNCTIONLIST = 4;
  public int JJTFUNCTIONDECLARATION = 5;
  public int JJTFUNCVARIABLEDECLARATION = 6;
  public int JJTTYPE = 7;
  public int JJTFUNCTIONDEFINITION = 8;
  public int JJTFUNCTION = 9;
  public int JJTDECLANDSTAT = 10;
  public int JJTVARIABLEDECLARATION = 11;
  public int JJTVOID = 12;
  public int JJTLESSTHAN = 13;
  public int JJTLESSEQUAL = 14;
  public int JJTGREATERTHAN = 15;
  public int JJTGREATEREQUAL = 16;
  public int JJTEQUAL = 17;
  public int JJTNOTEQUAL = 18;
  public int JJTPLUS = 19;
  public int JJTMINUS = 20;
  public int JJTMULTIPLY = 21;
  public int JJTDIVIDE = 22;
  public int JJTPOSITIVE = 23;
  public int JJTNEGATIVE = 24;
  public int JJTCONSTANTLITERAL = 25;
  public int JJTLITERAL = 26;
  public int JJTBOOLEANLITERAL = 27;
  public int JJTNAME = 28;
  public int JJTBLOCKSTATEMENT = 29;
  public int JJTASSIGNMENTSTATEMENT = 30;
  public int JJTCONTROLSTATEMENT = 31;
  public int JJTIFSTATEMENT = 32;
  public int JJTWHILESTATEMENT = 33;
  public int JJTRETURNSTATEMENT = 34;
  public int JJTERROR = 35;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "Constant",
    "NewType",
    "NewTypeDefinition",
    "FunctionList",
    "FunctionDeclaration",
    "FuncVariableDeclaration",
    "Type",
    "FunctionDefinition",
    "Function",
    "DeclAndStat",
    "VariableDeclaration",
    "void",
    "lessThan",
    "lessEqual",
    "greaterThan",
    "greaterEqual",
    "equal",
    "notEqual",
    "plus",
    "minus",
    "multiply",
    "divide",
    "positive",
    "negative",
    "ConstantLiteral",
    "Literal",
    "BooleanLiteral",
    "Name",
    "BlockStatement",
    "AssignmentStatement",
    "ControlStatement",
    "IfStatement",
    "WhileStatement",
    "ReturnStatement",
    "Error",
  };
}
/* JavaCC - OriginalChecksum=4aaa3bcbf89deb2b092c8efa8d378c9f (do not edit this line) */
