/* Generated By:JJTree: Do not edit this line. ASTNewTypeDefinition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wci.intermediate.icodeimpl.ICodeNodeImpl,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package teamAlumni.frontend;

public
class ASTNewTypeDefinition extends SimpleNode {
  public ASTNewTypeDefinition(int id) {
    super(id);
  }

  public ASTNewTypeDefinition(Assignment7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Assignment7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e3032472ad55b630a44ef7bb2b8d9dbf (do not edit this line) */
